matrix:
    include:
        - os: linux
          language: cpp
          env:
              - MATRIX_EVAL="export CXX=g++-6"
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-6

        - os: linux
          language: cpp
          env:
              - MATRIX_EVAL="export CXX=g++-7"
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-7

        - os: linux
          language: python
          python: "3.4"
          install:
              - pip install django
          script:
              - cd aura-server
              - ./manage.py migrate
              - ./manage.py test

        - os: linux
          language: python
          python: "3.5"
          install:
              - pip install django
          script:
              - cd aura-server
              - ./manage.py migrate
              - ./manage.py test

        - os: linux
          language: python
          python: "3.6"
          install:
              - pip install django
          script:
              - cd aura-server
              - ./manage.py migrate
              - ./manage.py test

# Default settings for C++ client build
before_install:
  - test -n $CXX && unset CXX
  - eval "${MATRIX_EVAL}"

script:
    - cd aura-client
    - cmake . -DCMAKE_BUILD_TYPE=Debug
    - make -j2
    - ctest --output-on-failure
